# GAME CONFIG
TITLE = 'Zombie Sunday'
WINDOW_SIZE = (1280, 600)
FPS = 60
RES_DIR = 'res'
FONT = 'res/fonts/ProggySquare.ttf'

# LEVEL POSITIONS
LOGO_POS = ((WINDOW_SIZE[0] / 2) - 338, 30)
BUTTON_START_POS = ((WINDOW_SIZE[0] / 2) - 165, 220)

SUN_POS = (WINDOW_SIZE[0] - 250, 20)
BACKGROUND_1_POS = (0, WINDOW_SIZE[1] - 245)
BACKGROUND_2_POS = (0, WINDOW_SIZE[1] - 192)
CLOUD_1_POS = (WINDOW_SIZE[0] - 100, 10)
CLOUD_2_POS = (WINDOW_SIZE[0] / 2, 200)
CLOUD_3_POS = (0, 100)
GROUND_POS = (0, WINDOW_SIZE[1] - 96)

PLAYER_POS = (10, WINDOW_SIZE[1] - 300)
HOME_POS = (5, WINDOW_SIZE[1] - 525)
ZOMBIE_POS = (0, WINDOW_SIZE[1] - 246)

# LEVEL CONFIG
LEVEL_SIZE = 10
GROUND_WIDTH = 1600
GROUND_HEIGHT = 96
TITLE_SCROLL_SPEED = 100

BUILDING_RANGE = [15, 25, 100] # [Min, max, multiplier]. randint(min, max) * multiplier
ZOMBIE_MAX = 10
ZOMBIE_SPAWN_TIME = 2 # In seconds

ZOMBIE_MAX_MOD = 1 # ZOMBIE_MAX += ZOMBIE_MAX_MOD * level.stage
ZOMBIE_SPAWN_TIME_MOD = .98 # ZOMBIE_SPAWN_TIME *= pow(ZOMBIE_SPAWN_TIME_MOD, level.stage)
ZOMBIE_HSPEED_MOD = 5 # ZOMBIE_HSPEED += ZOMBIE_HSPEED_MOD * level.stage
ZOMBIE_DAMAGE_MOD = 5 # ZOMBIE_DAMAGE += ZOMBIE_DAMAGE_MOD * level.stage
ZOMBIE_HEALTH_MOD = 10 # ZOMBIE_HEALTH += ZOMBIE_HEALTH_MOD * level.stage
ZOMBIE_ATTACK_RATE_MOD = .5 # ZOMBIE_ATTACK_RATE -= ZOMBIE_ATTACK_RATE_MOD * level.stage
ZOMBIE_SCORE_MOD = 10 # ZOMBIE_SCORE += ZOMBIE_SCORE_MOD * level.stage
BUILDING_DISTANCE_MOD = 20 # BUILDING_RANGE += BUILDING_DISTANCE_MOD * level.stage

# ENTITY CONFIG
ENTITY_GRAVITY = 20
ENTITY_VSPEED = 200
ENTITY_HSPEED = 200
ENTITY_HEALTH = 100

PLAYER_AMMO = 500
PLAYER_HEALTH = 100
PLAYER_HSPEED = 400

ZOMBIE_HEALTH = 100
ZOMBIE_HSPEED = 75
ZOMBIE_DAMAGE = 10
ZOMBIE_ATTACK_RATE = 1
ZOMBIE_SCORE = 100
